### PR TITLE
Feature/pro adjustable nozzles

### PR DESCRIPTION
**Pull request by fern-aviles**
What's new
-
- Pro Adjustable Nozzles data has been added to the database
- User can select the new nozzles added

Set Up
-
- Clone repo
- In your command line:
  - run npm install to install necessary packages
  - run npm run dev to run the project in your web browser

On your browser, go to localhost:5173 and you should see a page with input fields with a black line and text reading "5 feet" under it.

Testing
-
- Click to add a Pro Adjustable Nozzle
- There should be 7 different nozzles to choose from
- Changing the arc angle should also change the data for any Pro Adjustable nozzle
- Previous functionality should remain the same
  - Nozzles options change depending on the arc and radius
  - Nozzles become deselected if its arc or radius don't match the current water arc and radius
  - Clicking on a nozzle shows information based on the current water arc and radius

Bugs
-
- ~White flash when changing nozzles automatically is back~

### CODE REVIEW

**Review by scott-allison — CHANGES_REQUESTED** [review]
For Pro Adjustable Nozzles, if there are multiple nozzle options, the automatically selected nozzle choice should be the closest to the radius. Example: 12A and 10A can both be reduced to 9.9ft. However, 10A is closest, and should be selected.

PGP Ultra nozzle has no color. No auto-selected nozzle appears. Try adding a PGP Ultra and you'll see a white or transparent circle in the middle.

Everything else looks great. Working as expected. Code is clean and easy to follow. Data.json is well defined and consistent.

**Comment by fern-aviles** [comment]
> For Pro Adjustable Nozzles, if there are multiple nozzle options, the automatically selected nozzle choice should be the closest to the radius. Example: 12A and 10A can both be reduced to 9.9ft. However, 10A is closest, and should be selected.
> 
> PGP Ultra nozzle has no color. No auto-selected nozzle appears. Try adding a PGP Ultra and you'll see a white or transparent circle in the middle.
> 
> Everything else looks great. Working as expected. Code is clean and easy to follow. Data.json is well defined and consistent.

For Pro Adjustable Nozzles, the automatically selected nozzle now matches with the scenario above. If a nozzle that matches the radius closer appears, it auto-selects the new nozzle.

PGP Ultra is white if it has no nozzle selected (no auto-selection). When a nozzle is selected, it is black.

**Comment by scott-allison** [comment]
This needs work.

Max radius for Pro Adjustable Nozzles at 30 PSI is 17'. Currently this goes to 19' and the nozzle becomes white because nothing is selectable.

**Comment by scott-allison** [comment]
test

**Review by scott-allison — CHANGES_REQUESTED** [review]
Max radius for Pro Adjustable Nozzles at 30 PSI is 17'. Currently this goes to 19' and the nozzle becomes white because nothing is selectable.

Max and min radius should be enforced by the pressure entered, or the default for the product. Nozzle default = 30 PSI. MP Rotator default = 40 PSI. Rotor default = 45 PSI

**Comment by scott-allison** [comment]
Please merge all products into a single branch and submit for a review. Thanks!

As stated previously, everything looks great behavior-wise, except the min/max radius based on pressure. This will help us avoid situations where no nozzle is selectable.

**Pull request closed without merging**
