### PR TITLE
Feature/rotors and pro nozzles

### PR DESCRIPTION
**Pull request by fern-aviles**
What's new
-
- SRM, PGP-ADJ, PGJ, Pro Fixed Nozzles data has been added to the database

Set Up
-
- Clone repo
- In your command line:
  - run npm install to install necessary packages
  - run npm run dev to run the project in your web browser

On your browser, go to localhost:5173 and you should see a page with input fields with a black line and text reading "5 feet" under it.

Testing
-
- Click to add a product
- There should be nozzles selectable at both minimum radius and maximum radius for every product at every pressure
- Rotors should change display information depending on any slight change on their arc angle.
- Previous functionality should remain the same
  - Nozzles options change depending on the arc and radius
  - Nozzles become deselected if its arc or radius don't match the current water arc and radius
  - Clicking on a nozzle shows information based on the current water arc and radius

### CODE REVIEW

**Comment by scott-allison** [comment]
* 270-360 no longer snapping for MPs
* Default pressure - make the PSI input blank. Use recommended pressure as default for each product (PGP-Ultra = 45, MP = 40, Adjust/Fixed = 30, PGJ/SRM = 40, PGP-ADJ = 45)

**Review by scott-allison — CHANGES_REQUESTED** [review]
See comments.

**Review by fern-aviles — COMMENTED** [review]
Fixed MP Rotator not omitting angles and recommended pressure is the initial pressure if no custom pressure is entered.

**Review by scott-allison — CHANGES_REQUESTED** [review]
MP Rotator looks good now with omitted ranges. Thanks for fixing that.

Fixed nozzles still not omitting ranges.
1. Place the product
2. adjust the arc, any angle is fine
3. Increase radius, it selects the nozzle in the list but it's not enabled. The arc stays at whatever custom degree
 
Once I decrease it down to 120º then it starts snapping to the Q, H, T, F
 
Same thing if I don't change the radius.
1. Place the product
2. Adjust the arc, any degree angle works
3. Once you get to 180º then it starts snapping to QHTF

**Pull request merged**
